---
toc: true
---

# Welcome {.unnumbered}

::: {.callout-note}

The course will take place the week of 30 March - 3 April 2026. 

{{< fa hand-point-right >}}&nbsp; See the [FRB-CESAB website](https://www.fondationbiodiversite.fr/en/evenement/frb-cesab-analyse-de-reseaux-dinteractions-en-ecologie-2026/) for the pre-registration link.

More information is available on the [FRB-CESAB website](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/analyse-de-reseaux-dinteractions-en-ecologie/). 
Subscribe to the 
[FRB-CESAB newsletter](https://www.fondationbiodiversite.fr/en/newsletter/) to stay informed. 

:::

The objective of this five-day course is to train young researchers in analyzing ecological network data. The course covers a general introduction to networks, classical metrics (including modularity, nesteness, clustering), null models, generative models (including SBM), multilayer networks, as well as an overview of newer techniques (such as embedding). Each topic is explored through lectures followed by practicals.

The course is co-organized by the 
[FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)
and the
[ANR ECONET](https://cmatias.perso.math.cnrs.fr/ANR_EcoNet.html), and benefits from funding from the [PEPR Maths-Vives](https://www.maths-vives.fr/en/).   


## Program {.unnumbered}

Classes will run from 9am to 5:30pm every day except Friday, when we finish at 4pm. 


### Monday - Introduction

| **9:00**: *Welcome*
| **9:30**: Introduction to networks  
| **11:00**: *Coffee break*
| **11:30**: What kind of networks in ecology ? 
| **12:00**: How are ecological network data collected ? 
| **12:30**: *Lunch break*
| **14:00**: `igraph` 
| **15:30**: "Speed dating"
| **16:15**: *Coffee break*
| **16:30**: The structure of ecological networks
| **17:30**: End of the working day


### Tuesday - Network metrics and null models

| **9:00**: Metrics
| **10:30**: *Coffee break*
| **11:00**: Network models, null models
| **12:00**: *Lunch break* 
| **14:00**: Complexity stability
| **14:30**: The consequences of network structure 
| **15:30**: *Coffee break*
| **16:00**: Group projects
| **17:30**: End of the working day 


### Wednesday - Generative Stochastic Models

| **9:00**: Introduction to block models
| **10:30**: *Coffee break*
| **11:00**: Selecting the number of blocks
| **12:00**: *Lunch break* 
| **14:00**: The structure of ecological networks (2)
| **15:00**: *Coffee break*
| **15:30**: Group projects
| **17:30**: End of the working day 


### Thursday - Multilayer networks

| **9:00**: Multilayer networks in ecology
| **10:30**: *Coffee break*
| **11:00**: Multilayer in practice
| **12:00**: *Lunch break* 
| **14:00**: Group projects
| **17:30**: End of the working day 


### Friday - Opening and group presentations

| **9:00**: Motifs, embedding, collection of networks
| **10:30**: *Coffee break*
| **11:00**: finalizing presentations
| **12:00**: *Lunch break at the CESAB* 
| **14:00**: Group project presentations
| **16:30**: End of the course


## Prerequisites {.unnumbered}

{{< fa hand-point-right >}}&nbsp; Please follow this [tutorial](https://frbcesab.github.io/rsetup/) to install 
your working environment **before attending the training course**.
Only `R`, `RStudio Desktop`, and `Rtools` (for Windows users) are required for this course.

You also need to create an account on [GitHub](https://github.com/signup/).


## Material {.unnumbered}

All the data and extra functions needed during the course are available at:
<https://github.com/econetoolbox/data>


## The lecturers {.unnumbered}

[Sophie DONNET](https://sophiedonnet.github.io/) (INRAE, MIA Paris Saclay)
    
[Sonia KEFI](https://biodicee.edu.umontpellier.fr/who-we-are/sonia-kefi/) (CNRS, ISEM, Montpellier)
    
[François MASSOL](https://sites.google.com/a/polytechnique.org/francoismassol/home) (CNRS, iEES, Paris)
    
[Elisa THEBAULT](https://iees-paris.fr/annuaire/thebault-elisa/) (CNRS, iEES, Paris)

[Stéphane Robin](https://scj-robin.github.io/) (Sorbonne U., LPSM, Paris)


## Contributions {.unnumbered}

If you see mistakes or want to suggest changes, please [create an issue](https://github.com/econetoolbox/econetoolbox.github.io/issues/new) on the source repository.


## Reuse {.unnumbered}

Text and figures are licensed under Creative Commons Attribution [CC By 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted.


## See also {.unnumbered}

Discover the other training courses provided by the FRB-CESAB and its partners: <https://frbcesab.github.io/training-courses/>


